version: 2.1
jobs:
  test:
    docker:
      - image: hysds/pge-base:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: Test
          command: |
            source $HOME/verdi/bin/activate
            sudo yum -y update
            sudo yum -y install gcc
            cp $HOME/verdi/ops/hysds/configs/celery/celeryconfig.py.tmpl $HOME/verdi/ops/hysds/celeryconfig.py
            pip install -U pytest jsonschema
            pip install -e .
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports    


workflows:
  version: 2
  test:
    jobs:
      - test:
          context:
            - docker-hub-creds
            - git-oauth-token
  weekly:
    triggers:
      - schedule:
          cron: "0 7 * * 0"
          filters:
            branches:
              only:
                - develop
    jobs:
      - test:
          context:
            - docker-hub-creds
            - git-oauth-token
          filters:
            branches:
              only: develop
